[package]
edition = "2021"
name = "embassy-boot-rp-examples"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
embassy-sync = { version = "0.1.0", path = "../../../../embassy-sync", features = ["defmt"] }
embassy-executor = { version = "0.1.0", path = "../../../../embassy-executor", features = ["nightly", "integrated-timers"] }
embassy-time = { version = "0.1.0", path = "../../../../embassy-time", features = ["nightly"] }
embassy-rp = { version = "0.1.0", path = "../../../../embassy-rp", features = ["unstable-traits", "nightly", "time-driver"]  }
embassy-boot-rp = { version = "0.1.0", path = "../../../../embassy-boot/rp" }
embassy-embedded-hal = { version = "0.1.0", path = "../../../../embassy-embedded-hal" }

defmt = { version = "0.3", optional = true }
defmt-rtt = { version = "0.4", optional = true }
panic-reset = { version = "0.1.1" }
embedded-hal = { version = "0.2.6" }

cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.0"

[features]
defmt = [
      "dep:defmt",
      "embassy-rp/defmt",
      "embassy-boot-rp/defmt",
]
